config/routes.rb
Rails.application.routes.draw do
  devise_for :tusers
  devise_scope :tuser do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
 
  #resources :tusers, only: [:new, :create, :show, :index, :edit, :update]
  resources :tusers , :controller => "tusers"
  
  resources :job_offers do
    resources :applications, only: [:create, :destroy]
  end
  
  # Defines the root path route ("/")
  root "home#index"
end

app/views/navbars/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span class="work-logo">WORK</span><span class="wave-logo">WAVE</span>
    <% end %>

    <% if tuser_signed_in? && current_tuser.admin? %> 
      <%= link_to "Registro", new_tuser_path, class: "nav-link" %>
      <%= link_to "Nueva Oferta", new_job_offer_path, class: "nav-link" %>
    <% end %>

    <!--<% if tuser_signed_in? && current_tuser != @tuser %>
      <li class="nav-item">
        <%= link_to "Mis Postulaciones", tuser_path(current_tuser), class: "nav-link" %>
      </li>
    <% end %> -->

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto">
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if tuser_signed_in? %>
              Hola <%= current_tuser.email %>
            <% else %>
              Inicia Sesión
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if tuser_signed_in?%>
              <li><%= button_to "Cerrar Sesión", destroy_tuser_session_path, method: :delete, class: "dropdown-item" %></li>
               <% else %>
              <li><%= link_to "Iniciar Sesión", new_tuser_session_path , class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>