config/routes.rb
Rails.application.routes.draw do
  devise_for :tusers
  devise_scope :tuser do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
 
  #resources :tusers, only: [:new, :create, :show, :index, :edit, :update]
  resources :tusers , :controller => "tusers"
  
  resources :job_offers do
    resources :applications, only: [:create, :destroy]
  end
  
  # Defines the root path route ("/")
  root "home#index"
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
    has_many :applications, dependent: :destroy
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: %i[show edit update destroy]
  before_action :authenticate_tuser!, except: [:index, :show]
  before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]

  # GET /job_offers or /job_offers.json
  def index
    @job_offers = JobOffer.all
  end

  # GET /job_offers/1 or /job_offers/1.json
  def show
  end

  # GET /job_offers/new
  def new
    @job_offer = JobOffer.new
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers or /job_offers.json
  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully created." }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_offers/1 or /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully updated." }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_offers/1 or /job_offers/1.json
  def destroy
    @job_offer.destroy

    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: "Job offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_offer_params
      params.require(:job_offer).permit(:title, :description)
    end

    def authorize_esteban
      unless current_tuser && current_tuser.esteban?
        flash[:alert] = "Acceso denegado. Solo Esteban puede realizar esta acción."
        redirect_to root_path
      end
    end
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/views/job_offers/_form.html.erb
<%= form_with(model: job_offer) do |form| %>
  <% if job_offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_offer.errors.count, "error") %> prohibited this job_offer from being saved:</h2>

      <ul>
        <% job_offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :puesto, style: "display: block", class:"label" %>
    <%= form.text_field :title , class:"contenido" %>
  </div>

  <div>
    <%= form.label :descripción, style: "display: block" , class:"label" %>
    <%= form.text_area :description, class:"contenido" %>
  </div>

  <div>
    <%= form.submit  "ENVIAR", class:"boton-enviar"%>
  </div>
<% end %>

app/views/job_offers/_job_offer.html.erb
<div id="<%= dom_id job_offer %>">
  <p>
    <strong class="etiqueta">Puesto:</strong>
    <span class="data1"><%= job_offer.title %></span>
  </p>

  <p>
    <strong class="etiqueta">Descripción:</strong>
    <span class="data"><%= job_offer.description %></span>
  </p>
</div>

app/views/job_offers/edit.html.erb
<h1>Editing job offer</h1>

<%= render "form", job_offer: @job_offer %>

<br>

<div>
  <%= link_to "Show this job offer", @job_offer %> |
  <%= link_to "Back to job offers", job_offers_path %>
</div>

app/views/job_offers/index.html.erb
<body class="body-ofertas">
  <h1 class="titulo-oferta">Ofertas Laborales</h1>

  <div id="job_offers" class="card-container">
    <% @job_offers.each do |job_offer| %>
      <div class="card">
        <%= render job_offer %>
        <p>
          <%= link_to "Mostrar esta oferta", job_offer, class: "oferta-mostrar" %>
        </p>
      </div>
    <% end %>
  </div>
</body>

app/views/job_offers/new.html.erb
<body class="body-new-job">

<h1 class="titulo-nuevo">Nuevo Puesto</h1>

<%= render "form", job_offer: @job_offer %>

<br>

<div>
  <%= link_to " ◀ Volver a ofertas", job_offers_path, class:"link-vuelta-nuevo"%>
</div>

</body>

app/views/job_offers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_offer %>

<div>
  <%= link_to "Edit this job offer", edit_job_offer_path(@job_offer) %> |
  <%= link_to "Back to job offers", job_offers_path %>

  <%= button_to "Destroy this job offer", @job_offer, method: :delete %>
</div>

<%= render "aplications/form"%>